### ISSUE TITLE
set default branch to `develop`

### ISSUE THREAD

**Issue by matart15** [kazuooooo/hack#1]
set default branch to `develop`

**Comment by kazuooooo** [comment]
@matart15 
Do you mean We should use master branch?

**Comment by matart15** [comment]
no. its just there is only 3 files in `master` branch. So after `git clone ` I ended up on master branch with 3 files.

There is 2 options i think.
1. set `develop` as default branch
2. merge `develop` into `master`

But if you are thinking to use `master` for release or some other purpose, option 1 would be better.

**Comment by kazuooooo** [comment]
OK, I choose option 1 cuz I want to use master branch for release branch.
I changed default branch to develop and squash many original forked project commits and repush ed to develop branch.
(Sorry for  d1ae6993af9941379cba516c6aec4c2d3d779fd5 commit little bit strange. I backuped [original branch](https://github.com/kazuooooo/hack/commits/develop-bk))

**Comment by kazuooooo** [comment]
Thank you for your advise 😄
