### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by matart15** [kazuooooo/hack#2]
`yarn dev` game me this error.
```
{ Error: EACCES: permission denied, open '/Users/matar/Library/Application Support/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi/build/inject.js'
```

Solved it by givig permission on `build` folder

Looks like same isssue got fixed [here](https://github.com/MarshallOfSound/electron-devtools-installer/issues/63).

**Comment by kazuooooo** [comment]
Thanks I'll fix it.

**Comment by matart15** [comment]
Also what is the command to run application?. `yarn dev` gave me timer example.

**Comment by kazuooooo** [comment]
Normally I use

```
npm run dev
```

but I recloned, it loooks not working. (white blank view)
I'm checking it.

**Comment by kazuooooo** [comment]
@matart15 
I fixed installation problem above.

Before I also got error using yarn.

So could you try with npm?

```
npm install
npm run dev
```
(You may need to delete node_modules before run this command)

It should show view like this

<img width="1028" alt="hello_electron_react__ _1__npm_run_dev__electron_helper_" src="https://user-images.githubusercontent.com/6919381/34905651-bec975e8-f8a0-11e7-89a9-9af2922b0fd5.png">

ToTasks link is main view now( We need to delete counter app..)
thanks,
