### ISSUE TITLE
deleted tasks stays on array

### ISSUE THREAD

**Issue by matart15** [kazuooooo/hack#20]
Current `Action` is saving child task on array. So deleted tasks stays as null and index continues after that.
we should use some tree data structue like [this one](https://github.com/nylen/easy-tree) (if we stay with current UI).

**Comment by kazuooooo** [comment]
@matart15 
Yes, current hacking implementation needs to continue to have null object in array, because each task's path is nested array index.
We should fix this using some library like which you mention.
Can I assign you this issue?

**Comment by kazuooooo** [comment]
This bug is fixed by replacement with sortable tree #24
